# Generated by Django 4.1.2 on 2022-10-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cif', models.CharField(max_length=12)),
                ('ccaa', models.CharField(max_length=50)),
                ('sistemaEducativo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cod', models.CharField(max_length=12)),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=9)),
                ('fecha_nacimiento', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.grado')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cod', models.CharField(max_length=12)),
                ('creditos', models.IntegerField(default=6)),
                ('grados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.grado')),
            ],
        ),
    ]
