# Generated by Django 4.1.2 on 2022-11-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_grado_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='grados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='myapp.grado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='myapp.grado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='myapp.universidad'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='myapp.universidad'),
        ),
    ]
